apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: leps2408/mlflow-server:latest
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://172.23.73.213:9000"  # Cambia a la IP de tu máquina donde corre MinIO
        - name: AWS_ACCESS_KEY_ID
          value: "mi_usuario"  # Credenciales de MinIO
        - name: AWS_SECRET_ACCESS_KEY
          value: "mi_contraseña_segura"  # Credenciales de MinIO
        command: ["mlflow"]
        args:
        - "server"
        - "--host"
        - "0.0.0.0"
        - "--port"
        - "5000"
        - "--backend-store-uri"
        - "sqlite:///mlflow.db"
        - "--default-artifact-root"
        - "s3://mlflow-artifacts"  # Cambia el almacenamiento local a MinIO
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc  # Mantiene el volumen persistente para otros usos (si lo necesitas)
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: NodePort  # Cambia a LoadBalancer si es necesario
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000  # O cualquier puerto en el rango 30000-32767
  selector:
    app: mlflow-server

